### ISSUE TITLE
Unexpected value 'GridComponent'... Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by rnikiforova** [atatanasov/gijgo-angular-wrappers#2] opened 2018-03-28 12:59 UTC
# Unexpected value 'GridComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

I'm getting this error when trying to follow the Angular Grid demo (https://plnkr.co/edit/PpA8CxUCNFeTEqmjgbug). I was able to reproduce the problem in a clean Angular project.

**app.module.ts:**

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';


import { AppComponent } from './app.component';
import { GridComponent } from 'gijgo-angular-wrappers'

@NgModule({
  declarations: [
    AppComponent,
    GridComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**package.json**

```
{
  "name": "gijgo-angular-repro",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "^4.2.5",
    "@angular/core": "^4.2.5",
    "@angular/forms": "^4.2.5",
    "@angular/http": "^4.2.5",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "^4.2.5",
    "@angular/router": "^4.2.5",
    "@types/gijgo": "^1.8.1",
    "core-js": "^2.4.1",
    "gijgo": "^1.9.3",
    "gijgo-angular-wrappers": "^1.9.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^4.2.5",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.1",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

I believe the error is caused by incompatible Angular version. The error was **not** present when using Angular 5.2.0. However, it is present when the version is 4.2.5 (which I actually use). Also to make it work using Angular 5.2.0 I had to add "node_modules/gijgo-angular-wrappers" to `include` in `tsconfig.app.json`

Can you advice how the wrappers can be used on 4x or using 5+ is mandatory?

**Comment by atatanasov** [comment] 2018-03-28 14:20
The library is tested only with Angular 5+, but everything should be fine with Angular 4. In the following example everything looks good with Angular 4.2.5 https://plnkr.co/edit/KuyuND?p=preview. I guess that the issue is not related with the gijgo wrappers for Angular.

**Comment by atatanasov** [comment] 2018-04-02 08:58
I will close the issue. Let me know if you can prove that the issue is related with gijgo and I will reopen it.

**Closed by atatanasov** 2018-04-02 08:58 UTC
